### ISSUE TITLE
hello_world/example.env

### ISSUE THREAD

**Issue by jlaunay** [gmaron/django-hello-world#3]
Hi, could you please add example.env in the repository as explained in the README ?

**Comment by gmaron** [comment]
Hi @jlaunay,

Thanks for your feedback. 

The file that you are looking for is [hello_world/example.env](https://github.com/gmaron/django-hello-world/blob/231d09d27019f9ccc4cf1936903ac6bd6f754578/hello_world/settings.py).

I have to update the README.md file due to I am using `django-split-settings` to manage the environments. 

Have a nice day!
